#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_x86_64

# Add a button to trigger the workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO_URL: https://github.com/openwrt/openwrt.git
      REPO_TAG: v23.05.2
      TARGET_CONFIG: 'x86_64'
      DEBUG: true

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
        sudo -E apt-get update
        sudo -E apt-get -y install install build-essential clang flex bison g++ gawk cc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone OpenWrt Repository
      run: |
        git clone $REPO_URL openwrt
        cd openwrt
        git checkout $REPO_TAG

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone Argon Theme
      working-directory: ./openwrt
      run: |
        git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

    - name: Clone Adguardhome
      working-directory: ./openwrt
      run: |
        git clone https://github.com/kongfl888/luci-app-adguardhome.git package/luci-app-adguardhome

    - name: Clone Mosdns
      working-directory: ./openwrt
      run: |
        rm -rf feeds/packages/net/v2ray-geodata
        git clone https://github.com/sbwml/luci-app-mosdns.git -b v5 package/luci-app-mosdns
        git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata

    - name: Clone OpenClash
      working-directory: ./openwrt
      run: |
        git clone --depth=1 https://github.com/vernesong/OpenClash.git
        mv OpenClash/luci-app-openclash  package/luci-app-openclash
        rm -rf ./OpenClash

    - name: Configuration Customization
      run: |
        CONFIG_FILE="$TARGET_CONFIG.config"
        test -e $CONFIG_FILE && echo "The config file exists" || echo "The config file doesn't exists"
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-official-openwrt
      with:
        path: |
          openwrt/feeds
          openwrt/feeds.conf
          openwrt/build_dir/toolchain*
          openwrt/staging_dir/toolchain*
          openwrt/tmp
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{REPO_TAG}}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{REPO_TAG}}

    - name: Build Firmware
      working-directory: ./openwrt
      if: ${{ !DEBUG }}
      run: |
        echo -e "$(nproc) thread build."
        make -j $(($(nproc)+1)) defconfig download clean world

    - name: Build Firmware - DEBUG
      working-directory: ./openwrt
      if: ${{ DEBUG }}
      run: |
        echo -e "build - DEBUG mode"
        make -j1 V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
